sdm845-common: releasetools: decode android_info instead of encoding string pattern
Traceback (most recent call last):
AddTrustZoneAssertion(info, info.input_zip)
m = re.search(r'require\s+version-trustzone\s*=\s*(\S+)'.encode('utf-8'), android_info)
TypeError: cannot use a string pattern on a bytes-like object
ninja failed with: exit status 1

Signed-off-by: ibratabian17 <ibratabian@gmail.com>